[HAYS-946]Adding a new endpoint /auth to  authenticate user
freshworksinc/haystack-services pull request #3
Opened 2020-11-18 11:51 UTC by Krishna-Vishwakarma

Freshrelease ticket #: HAYS-946

Adding a new endpoint /auth/{product}/{userId} to authenticate user.

2020-11-19 03:45 UTC, sudhircirra requested changes
Please check the code formatting.

2020-11-19 03:45 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/controller/HaystackResource.java
> +    return Response.status(HttpStatus.BAD_REQUEST_400).entity(response).type(MediaType.APPLICATION_JSON).build();
Please log all the errors. It would be easier for us to debug.

2020-11-19 03:45 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/datastore/UserProductMappingDAO.java
> +  public UserProductMapping findById(Session session, String userId) throws NotFoundException {
Check the Code formatting here. Use the formatting from Search service code base.

2020-11-19 03:45 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/response/RouterTeamsResponse.java
> +public class RouterTeamsResponse {
Why is this called the `RouterTeamsResponse`? The response may be sent by router, but it doesn't mean that we have to call it that. And do we really need an entity for the response?

2020-11-19 03:45 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/service/HaystackService.java
> +      LOG.error("Exception occurred while getting teams from router service");
What exception occurred here? Log the exception. And it is not a good practice to catch the generic `Exception`, be specific with exceptions.

2020-11-19 03:45 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/service/UserProductMappingService.java
> +  public boolean userExists(String email) {
I don't see this method being used anywhere other than the test cases. Is this required?

2020-11-19 08:03 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/controller/HaystackResource.java
> +    return Response.status(HttpStatus.BAD_REQUEST_400).entity(response).type(MediaType.APPLICATION_JSON).build();
Provided Logs

2020-11-19 08:03 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/datastore/UserProductMappingDAO.java
> +  public UserProductMapping findById(Session session, String userId) throws NotFoundException {
I used the same pmdRules here, Once again I will formate and push

2020-11-19 08:03 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/response/RouterTeamsResponse.java
> +public class RouterTeamsResponse {
I have to check first whether requested teams are available or not for that
When we call router service API using http get request then it returns a json as a string '{"message":["freshdesk","freshworks-search"]}'

To parse this json I have written RouterTeamsResponse class and this line so that I get List<String> 
List<String> availableTeams = JsonUtil.readValue(this.routerService.getTeams(), RouterTeamsResponse.class);

Naming convention : I adopted same name convention which previous developer has used entire project.But I will welcome your suggestions

2020-11-19 08:07 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/service/HaystackService.java
> +      LOG.error("Exception occurred while getting teams from router service");
Logged the exception with appropriate custom message

2020-11-19 08:12 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/service/UserProductMappingService.java
> +  public boolean userExists(String email) {
I was using this method before but when changed from /auth to /auth/{product}/{userId} and it was being used in test cases so it did not show unused method that is why I forgot to remove . Removed now

2020-12-02 03:07 UTC, sudhircirra requested changes

2020-12-02 03:07 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/datastore/UserProductMappingDAO.java
> +  public UserProductMapping findById(Session session, String userId) throws NotFoundException {
PMD is for code linting. It cannot format the code. The code formatting has to be done from within the IDE. Are you mentioning to something else?

2020-12-02 03:07 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/response/RouterTeamsResponse.java
> +public class RouterTeamsResponse {
This looks to be a new class, and let us start by renaming this. For other occurrences you can refactor and raise a separate PR.

2020-12-03 08:33 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/datastore/UserProductMappingDAO.java
> +  public UserProductMapping findById(Session session, String userId) throws NotFoundException {
I have used fd.search.xml file which sesha has shared with me on very first day when I was working on haystack-proxy. Should we use anything else than this ??

2020-12-03 08:58 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/router/response/RouterTeamsResponse.java
> +public class RouterTeamsResponse {
Ok, Now for this new class file I will use Internal Project name as prefix like **HaystackTeamsResponse** and once all 4 PRs done then I will create a separate PR to Improve naming convention.

2020-12-04 13:38 UTC, sudhircirra approved these changes
LGTM. Added a comment on formatting.

2020-12-04 13:38 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/datastore/UserProductMappingDAO.java
> +  public UserProductMapping findById(Session session, String userId) throws NotFoundException {
With that there should be a new line between the class declaration and the next line.

2020-12-05 14:47 UTC, merged