[HAYS-1089]Providing update user feature for Trigmetry user
freshworksinc/haystack-services pull request #5
Opened 2020-12-01 18:43 UTC by Krishna-Vishwakarma

Changes in this PR intelligently perform create and update user operation

For example :
1. Create New Trigmetry user
2. User role can be changed
3. Add user to new organisation

2020-12-02 03:29 UTC, sudhircirra requested changes

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +  public String execute(TrigmetryRequest trigmetryRequest) throws Exception {
add comments at each step on what we are trying to achieve. It will be easy for folks reading the code.

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    GrafanaUserCretationReponse grafanaUserCretationReponse = null;
The class name of `GrafanaUserCreationRespone` is not good. We should be removing these very specific names and replace them. Using internal project names like `Trigmetry` is fine.

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    catch (Exception ex) {
Catching `Exception` will catch all exception. Do we need this here? Can we catch specific exceptions and will catching specific exceptions have any impact? Please check this at other places too.

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +        if (!role.equals("Viewer")) {
Can we use a string constant here?

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    if (responseMessage.equals("success")) {
Instead of checking on a string, can we use a boolean variable for this? Something like `isSuccessful`.

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +            responseMessage = "Failed to update role: " + role;
Why assign to a variable here? Instead the message can be directly logged.

2020-12-02 03:29 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +      LOG.info("Creating new user :" + name);
I see lot of `LOG.info` statements, where just some information is being logged which I believe are more debug statements. Can you take a relook at the the `info` statements and see where all we can change them to `debug` statements.

2020-12-04 06:36 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +  public String execute(TrigmetryRequest trigmetryRequest) throws Exception {
Added comments

2020-12-04 06:36 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    GrafanaUserCretationReponse grafanaUserCretationReponse = null;
Renamed

2020-12-04 06:36 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +        if (!role.equals("Viewer")) {
Changed

2020-12-04 12:34 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    catch (Exception ex) {
Changed to specific exception whatever code comes under this pr

2020-12-04 12:37 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +    if (responseMessage.equals("success")) {
I wanted to return specific messages as a response message that is why I was returning string. Changed to boolean type and now throwing specific messages as an exception from TrigmetryService file and handling in Resource class.

2020-12-04 12:39 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +            responseMessage = "Failed to update role: " + role;
I wanted to return specific messages as a response message that is why I was assigning specific message to a common variable and returning

2020-12-04 12:39 UTC, Krishna-Vishwakarma commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +      LOG.info("Creating new user :" + name);
Changed to debug and in Logging PR I will improve logging

2020-12-04 13:56 UTC, sudhircirra approved these changes
Please check the comment I provided before you merge the PR.

2020-12-04 13:56 UTC, sudhircirra commented on usermanagement/src/main/java/com/freshworks/haystack/usermanagement/trigmetry/service/TrigmetryService.java
> +//    Extracting user name from email
The comment `//` is there at the start of the line. It doesn't look right. Have this at the start of the comment and see that the comment line is properly indented and inline with the indentation of the code. Please check this at other places as well.

2020-12-04 18:00 UTC, merged